name: pantau

services:
  monitor:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PUBLIC_APP_NAME: ${PUBLIC_APP_NAME}
        DATABASE_URL: ${DATABASE_URL}
    container_name: pantau
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    volumes:
      - monitor_data:/data

volumes:
  monitor_data:
    driver: local
